### ISSUE TITLE
Clicking "External URL" opens the external URL in 2 tabs. 

### ISSUE THREAD

**Issue by BobbyMcWho** [ProjectWyvern/exchange.projectwyvern.com#1]
Likelihood: High
Impact: Low

Steps to reproduce: Visit the exchange site, and click the "External URL" button on any listed asset.

**Comment by protinam** [comment]
I have tried unsuccessfully (on vanilla Chrome, latest) to replicate this. Can you provide an exact link on which this happens?

**Comment by protinam** [comment]
Closing this, but feel free to reopen if you can replicate the issue and document steps taken.
