### ISSUE TITLE
Multiple Sell orders for the same asset can be placed. 

### ISSUE THREAD

**Issue by BobbyMcWho** [ProjectWyvern/exchange.projectwyvern.com#15]
Steps to reproduce: 
Go to Assets page
Click 3 Dots on an asset and select sell
Enter auction details
Confirm transaction
View "Find" Page
Confirm same asset is there multiple times
(Note that I did this with an Ethercraft item, but I only possessed 1 of that item from pre-sale)

**Comment by protinam** [comment]
This is true; it's not unintentional - once one order is matched, the other will be automatically removed (and can no longer be matched even if the user had a cached page).

I realize it may be confusing. The orderbook server could block multiple sell-side submissions of the same asset.

**Comment by BobbyMcWho** [comment]
If that does function as described, then the main concern shifts to a potential "attack" on the exchange, where an asset is deposited, and then the owner spams the order book with the same asset over and over. Since this only requires a signature, and not any gas cost, the order book would be overwhelmed.

**Comment by protinam** [comment]
The orderbook server rate limits requests (order submission requests moreso), and there is no incentive for a party to submit multiple identical orders. Further limiting measures could be imposed if necessary.

At the moment, however, I agree that the use cases requiring multiple orders for the same asset are unlikely, and this behavior is confusing.

Moved to https://github.com/ProjectWyvern/example-orderbook-server/issues/2 (this must be implemented server-side).
